server:
  port: 8080
mybatis-plus:
  type-aliases-package: com.rui.order.pojo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-order?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: order-nacos-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos 服务地址
logging:
  level:
    com.rui: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
