server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes: # 路由配置
        - id: user-gateway-service # 路由ID自定义，唯一
#          uri: http://127.0.0.1:8081 # 路由目标地址 http 就是固定地址
          uri: lb://user-gateway-service # 路由目标地址 lb 就是负载均衡
          predicates: # 路由断言，判断请求是否符合路由规则的条件
            - Path=/user/** # 路径断言，按照这个路径匹配，以 /user/ 开头
        - id: order-gateway-service # 路由ID自定义，唯一
            #          uri: http://127.0.0.1:8081 # 路由目标地址 http 就是固定地址
          uri: lb://order-gateway-service # 路由目标地址 lb 就是负载均衡
          predicates: # 路由断言，判断请求是否符合路由规则的条件
            - Path=/order/** # 路径断言，按照这个路径匹配，以 /order/ 开头
