logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 10.211.55.9
    port: 5672
    virtual-host: /
    username: rui
    password: 123456
    listener:
      simple:
        prefetch: 1 # 预取
