spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9999/cloud-auth/oauth/public-key'
  redis:
    host: 182.92.152.31
    port: 6379
    password: 123456
    timeout: 5000
    database: 0
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最小空闲
        min-idle: 4
        # 链接超时
        max-wait: 5000
        # 最大空闲
        max-idle: 8
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true
      routes:
        - id: 认证中心
          uri: lb://cloud-auth
          predicates:
            - Path=/cloud-auth/**
          filters:
            - StripPrefix=1
        - id: 系统服务
          uri: lb://cloud-admin
          predicates:
            - Path=/cloud-admin/**
          filters:
            - StripPrefix=1
